### ISSUE TITLE
Lost connection to redis

### ISSUE THREAD

**Issue by Marusyk** [element-hq/synapse#16998]
### Description

Every few sec I got redis disconnection (see logs). Please suggest where could be an issue?

config:

```
redis:
  enabled: true
  host: "redis-ndev.redis.cache.windows.net"
  port: 6380
  password: "..."
  dbid: 0
```

### Steps to reproduce

- just run service

### Homeserver

own homeserver

### Synapse Version

1.102.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL

### Workers

Single process

### Platform

Docker & k8s

### Relevant log output

```shell
2024-03-16 23:53:12,351 - synapse.replication.tcp.redis - 306 - INFO - sentinel- Connection to redis server redis-ndev.redis.cache.windows.net:6380 lost: Connection to the other side was lost in a non-clean fashion.
2024-03-17 00:09:15,369 - synapse.replication.tcp.redis - 204 - INFO - sentinel- Lost connection to redis
2024-03-17 00:09:15,369 - synapse.replication.tcp.redis - 306 - INFO - sentinel- Connection to redis server redis-ndev.redis.cache.windows.net:6380 lost: Connection was aborted locally using ITCPTransport.abortConnection.
2024-03-17 00:09:20,331 - synapse.replication.tcp.redis - 292 - INFO - sentinel- Connecting to redis server redis-ndev.redis.cache.windows.net:6380
2024-03-17 00:09:20,356 - synapse.replication.tcp.redis - 126 - INFO - sentinel- Connected to redis
2024-03-17 00:09:20,356 - synapse.replication.tcp.redis - 138 - INFO - subscribe-replication-35- Sending redis SUBSCRIBE for ['zulu.dev/USER_IP', 'zulu.dev']
2024-03-17 00:09:21,352 - synapse.replication.tcp.redis - 204 - INFO - sentinel- Lost connection to redis
2024-03-17 00:09:21,352 - synapse.metrics.background_process_metrics - 253 - ERROR - subscribe-replication-35- Background process 'subscribe-replication' threw an exception
Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/synapse/metrics/background_process_metrics.py", line 251, in run
      return await func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/synapse/replication/tcp/redis.py", line 139, in _send_subscribe
     await make_deferred_yieldable(self.subscribe(fully_qualified_stream_names))
   File "/usr/local/lib/python3.11/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
     current.result = callback(  # type: ignore[misc]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/txredisapi.py", line 534, in handle_reply
      raise r
  txredisapi.ConnectionError: Lost connection
2024-03-17 00:09:21,353 - synapse.replication.tcp.redis - 306 - INFO - sentinel- Connection to redis server redis-ndev.redis.cache.windows.net:6380 lost: Connection to the other side was lost in a non-clean fashion.
2024-03-17 00:09:21,354 - twisted - 282 - INFO - sentinel- Redis error: could not auth: Lost connection
2024-03-17 00:09:21,354 - synapse.replication.tcp.redis - 306 - INFO - sentinel- Connection to redis server redis-ndev.redis.cache.windows.net:6380 lost: Connection to the other side was lost in a non-clean fashion.
```

**Comment by Marusyk** [comment]
The problem is that by default `use_tls: false` for Redis configuration.
In my case, No-SSL port 6379 is disabled for the Redis instance. So, the `use_tls` should be set to `true`
![image](https://github.com/element-hq/synapse/assets/9221694/5530227a-69eb-47fa-8f23-d2c09c4e8274)
