### ISSUE TITLE
"Unable to restore session. We encountered an error trying to restore your previous session" when reopening Element

### ISSUE THREAD

**Issue by senspooky** [element-hq/synapse#17719]
### Description

When launching Element, the following message appears each time.

![image](https://github.com/user-attachments/assets/6e7b6e48-0058-4379-86ce-cfe6f0411a73)

If I clear storage, Element hangs on loading indefinitely until I exit Element and reload, at which point it asks me to sign-in again. Once I exit Element and reopen it, the message appears again.

While signed in, all previous messages remain encrypted and do not decrypt, despite verifying the session with my phone. 

### Steps to reproduce

- Open Element, sign in, verify session.
- On reopening element, the following message appears, the error message appears.

### Homeserver

matrix.lumity.chat

### Synapse Version

1.114.0

### Installation Method

Docker (matrixdotorg/synapse)

### Database

Single PostgreSQL server, not previously ported, not previously restored from backup?

### Workers

Single process

### Platform

Deployed via [Matrix server setup using Ansible and Docker](https://github.com/spantaleev/matrix-docker-ansible-deploy)
Running on an Ubuntu 22.04 VM. Synapse and all other related services are running in Docker containers.

### Configuration

- Synapse Admin
- Dimension
- Hookshot
- Coturn
- Sliding Sync

#### issue.txt
```
text = User did not supply any additional text.
app = element-web
version = 1.11.77
user_agent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.77 Chrome/126.0.6478.234 Electron/31.4.0 Safari/537.36
installed_pwa = false
touch_input = false
user_id = @##########:lumity.chat
device_id = LXZZNBWCFH
matrix_hs_server_version = 1.114.0
enabled_labs = feature_new_room_decoration_ui, feature_release_announcement
mx_local_settings = {"language":"en","feature_rust_crypto":true,"deviceNotificationsEnabled":true,"widgetOpenIDPermissions":{"allow":["!JBlSGLHMKrnyyamSdA%3Alumity.chat%3A%3Ahttps%3A%2F%2Fmatrix.lumity.chat%2Fhookshot%2Fwidgetapi%2Fv1%2Fstatic%2F%23%2F%3Fkind%3DroomConfig%26roomId%3D%24matrix_room_id%26widgetId%3D%24matrix_widget_id"],"deny":[]}}
storageManager_persisted = true
storageManager_quota = 39957750764
storageManager_usage = 14181356
storageManager_usage_indexedDB = 14181356
```

#### log-0,log
```
2024-09-17T03:37:53.824Z D Initialised rageshake.
2024-09-17T03:37:53.824Z D To fix line numbers in Chrome: Meatball menu ’ Settings ’ Ignore list ’ Add /rageshake\.ts & /logger\.ts$
2024-09-17T03:37:53.825Z D Using Electron platform
2024-09-17T03:37:53.828Z error Unhandled promise rejection: ReferenceError: Cannot access 'U' before initialization
2024-09-17T03:37:53.828Z error Unhandled promise rejection: ReferenceError: Cannot access 'U' before initialization
2024-09-17T03:37:53.828Z error Unhandled promise rejection: ReferenceError: Cannot access 'U' before initialization
2024-09-17T03:37:53.830Z D Configuring rageshake persistence...
2024-09-17T03:37:53.861Z D set language to en
2024-09-17T03:37:54.249Z D Application is running in production mode
2024-09-17T03:37:54.249Z D Vector starting at vector://vector/webapp/
2024-09-17T03:37:54.249Z D Verifying homeserver configuration
2024-09-17T03:37:54.250Z D Config uses a default_server_name - doing .well-known lookup
2024-09-17T03:37:54.250Z W DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
2024-09-17T03:37:54.331Z D rageshake: reached size limit while processing instance 7/7 (instance-zPw7Xwspc7n0NN1h), with 7037903 bytes of logs: will drop further instances
2024-09-17T03:37:55.167Z D FetchHttpApi: --> GET https://matrix-client.matrix.org/_matrix/client/unstable/org.matrix.msc2965/auth_issuer
2024-09-17T03:37:55.534Z D FetchHttpApi: <-- GET https://matrix-client.matrix.org/_matrix/client/unstable/org.matrix.msc2965/auth_issuer [367ms 404]
2024-09-17T03:37:55.536Z D Using homeserver config: {"hsUrl":"https://matrix-client.matrix.org","hsName":"matrix.org","hsNameIsDifferent":true,"isUrl":"https://vector.im","isDefault":true,"warning":null,"isNameResolvable":true}
2024-09-17T03:37:55.536Z D Updating SdkConfig with validated discovery information
2024-09-17T03:37:55.543Z I getSessionLock[8d81cd20-4280-4c00-9557-766f11b9fbf6] No other session has the lock: proceeding with startup
2024-09-17T03:37:55.555Z D No pickle key available
2024-09-17T03:37:55.555Z D Restoring session for @########:lumity.chat
2024-09-17T03:37:55.555Z D setLoggedIn: mxid: @########:lumity.chat deviceId: LXZZNBWCFH guest: false hs: https://matrix.lumity.chat/ softLogout: false  freshLogin: false
2024-09-17T03:37:55.555Z D StorageManager: Checking storage consistency
2024-09-17T03:37:55.555Z D StorageManager: Local storage supported? true
2024-09-17T03:37:55.555Z D StorageManager: IndexedDB supported? true
2024-09-17T03:37:55.555Z D StorageManager: Local storage contains data? true
2024-09-17T03:37:55.555Z D StorageManager: Crypto initialised? true
2024-09-17T03:37:55.556Z D StorageManager: Sync store using IndexedDB contains data? true
2024-09-17T03:37:55.557Z D StorageManager: Rust Crypto store using IndexedDB contains data? true
2024-09-17T03:37:55.557Z D StorageManager: Storage consistency checks passed
2024-09-17T03:37:55.574Z E Expected a pickle key, but none provided.  Encryption may not work.
2024-09-17T03:37:55.574Z I Default empty persistCredentials() => void
2024-09-17T03:37:55.574Z D Session persisted for @########:lumity.chat
2024-09-17T03:37:55.574Z D Lifecycle: Starting MatrixClient
2024-09-17T03:37:55.578Z D FetchHttpApi: --> GET https://matrix.lumity.chat/_matrix/client/v3/thirdparty/protocols
2024-09-17T03:37:55.599Z D EventIndex: Event indexing isn't installed for the platform, not initializing.
2024-09-17T03:37:55.599Z D IndexedDBStore.startup: connecting to backend
2024-09-17T03:37:55.600Z D MatrixClientPeg: waiting for MatrixClient store to initialise
2024-09-17T03:37:55.600Z D StorageManager: Persistent? true
2024-09-17T03:37:55.601Z D Switching to room id !HYxDGbNMKVPSfGFbaw:lumity.chat at event undefined
2024-09-17T03:37:55.628Z D IndexedDB worker is ready
2024-09-17T03:37:55.629Z D FetchHttpApi: <-- GET https://matrix.lumity.chat/_matrix/client/v3/thirdparty/protocols [51ms 401]
2024-09-17T03:37:55.629Z D Failed to check for protocol support: will retry MatrixError: [401] Missing access token (https://matrix.lumity.chat/_matrix/client/v3/thirdparty/protocols)
M_MISSING_TOKEN: MatrixError: [401] Missing access token (https://matrix.lumity.chat/_matrix/client/v3/thirdparty/protocols)
    at p (vector://vector/webapp/bundles/c87c7a86acf04049be8f/119.js:2:457718)
    at O.requestOtherUrl (vector://vector/webapp/bundles/c87c7a86acf04049be8f/119.js:2:462355)
    at async O.authedRequest (vector://vector/webapp/bundles/c87c7a86acf04049be8f/119.js:2:460181)
    at async te.checkProtocols (vector://vector/webapp/bundles/c87c7a86acf04049be8f/119.js:2:1177108)
2024-09-17T03:37:55.655Z D IndexedDBStore.startup: loading presence events
2024-09-17T03:37:55.657Z D IndexedDBStore.startup: processing presence events
2024-09-17T03:37:55.659Z E Warning! Not using an encryption key for rust crypto store.
2024-09-17T03:37:55.659Z D Downloading Rust crypto library
2024-09-17T03:37:55.749Z D Initialising Rust crypto-sdk WASM artifact
2024-09-17T03:37:55.883Z D Opening Rust CryptoStore
2024-09-17T03:37:55.886Z D DEBUG matrix_sdk_indexeddb::crypto_store: IndexedDbCryptoStore: opening main store matrix-js-sdk::matrix-sdk-crypto
    at /home/runner/.cargo/git/checkouts/matrix-rust-sdk-1f4927f82a3d27bb/d9b2b53/crates/matrix-sdk-indexeddb/src/crypto_store/mod.rs:263
2024-09-17T03:37:55.911Z D Init OlmMachine
2024-09-17T03:37:55.921Z E Unable to load session An object failed to be decrypted while unpickling
Error: An object failed to be decrypted while unpickling
    at A.exports.__wbindgen_error_new (vector://vector/webapp/bundles/c87c7a86acf04049be8f/7490.js:1:106731)
    at matrix_sdk_crypto_wasm.wasm.<wasm_bindgen::JsError as core::convert::From<E>>::from::h55cec2b0d95a6df1 (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[2716]:0x2c9b38)
    at matrix_sdk_crypto_wasm.wasm.matrix_sdk_crypto_wasm::machine::OlmMachine::init_helper::{{closure}}::h7d41058b3bef5a87 (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[233]:0x4393a)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h468933eb85fd6349 (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[509]:0x116e03)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen_futures::queue::Queue::new::{{closure}}::hee45b573e253a33d (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[7405]:0x39ad24)
    at matrix_sdk_crypto_wasm.wasm.wasm_bindgen::convert::closures::invoke1_mut::hd6ac503cc1b2bedc (wasm://wasm/matrix_sdk_crypto_wasm.wasm-017a72fa:wasm-function[8645]:0x3ac97a)
    at L (vector://vector/webapp/bundles/c87c7a86acf04049be8f/7490.js:1:3400)
    at E (vector://vector/webapp/bundles/c87c7a86acf04049be8f/7490.js:1:2422)
2024-09-17T03:38:00.799Z D Sending bug report.
2024-09-17T03:38:00.802Z D FetchHttpApi: --> GET https://matrix.lumity.chat/_synapse/admin/v1/server_version
2024-09-17T03:38:00.814Z D FetchHttpApi: <-- GET https://matrix.lumity.chat/_synapse/admin/v1/server_version [12ms 200]

```

**Comment by senspooky** [comment]
Apologies, this was raised on the wrong repo.
