### ISSUE TITLE
cannot import name 'delayed_events'

### ISSUE THREAD

**Issue by renaudallard** [element-hq/synapse#17778]
### Description

I compiled synapse 1.116.0. Everything went OK, but when I tried to start it, I get a new error which seems related to the new delayed events.

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/synapse/app/homeserver.py", line 43, in <module>
    from synapse.app import _base
  File "/usr/local/lib/python3.10/site-packages/synapse/app/_base.py", line 71, in <module>
    from synapse.events.auto_accept_invites import InviteAutoAccepter
  File "/usr/local/lib/python3.10/site-packages/synapse/events/auto_accept_invites.py", line 28, in <module>
    from synapse.module_api import EventBase, ModuleApi, run_as_background_process
  File "/usr/local/lib/python3.10/site-packages/synapse/module_api/__init__.py", line 58, in <module>
    from synapse.handlers.account_data import ON_ACCOUNT_DATA_UPDATED_CALLBACK
  File "/usr/local/lib/python3.10/site-packages/synapse/handlers/account_data.py", line 27, in <module>
    from synapse.replication.http.account_data import (
  File "/usr/local/lib/python3.10/site-packages/synapse/replication/http/__init__.py", line 24, in <module>
    from synapse.replication.http import (
ImportError: cannot import name 'delayed_events' from partially initialized module 'synapse.replication.http' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/synapse/replication/http/__init__.py)
doing rc_check
synapse.app.homeserver(/var/synapse/homeserver.yaml) failed to start (exit code: 1). Check the Synapse logfile, or run synctl with --no-daemonize.
`

### Steps to reproduce

Compile synapse 1.116.0 on OpenBSD 7.5 (or -current) amd64.
Try to start synapse.

### Homeserver

matrix.arnor.org

### Synapse Version

1.116.0

### Installation Method

Other (please mention below)

### Database

SQLite

### Workers

Single process

### Platform

OpenBSD 7.5 and OpenBSD -current running on amd64

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/site-packages/synapse/app/homeserver.py", line 43, in <module>
    from synapse.app import _base
  File "/usr/local/lib/python3.10/site-packages/synapse/app/_base.py", line 71, in <module>
    from synapse.events.auto_accept_invites import InviteAutoAccepter
  File "/usr/local/lib/python3.10/site-packages/synapse/events/auto_accept_invites.py", line 28, in <module>
    from synapse.module_api import EventBase, ModuleApi, run_as_background_process
  File "/usr/local/lib/python3.10/site-packages/synapse/module_api/__init__.py", line 58, in <module>
    from synapse.handlers.account_data import ON_ACCOUNT_DATA_UPDATED_CALLBACK
  File "/usr/local/lib/python3.10/site-packages/synapse/handlers/account_data.py", line 27, in <module>
    from synapse.replication.http.account_data import (
  File "/usr/local/lib/python3.10/site-packages/synapse/replication/http/__init__.py", line 24, in <module>
    from synapse.replication.http import (
ImportError: cannot import name 'delayed_events' from partially initialized module 'synapse.replication.http' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/synapse/replication/http/__init__.py)
doing rc_check
synapse.app.homeserver(/var/synapse/homeserver.yaml) failed to start (exit code: 1). Check the Synapse logfile, or run synctl with --no-daemonize.
```

**Comment by renaudallard** [comment]
It seems the issue was with some dependencies. I uninstalled python and made some cleaning and it compiled and started without issue. Sorry for the noise.
