### ISSUE TITLE
Can't generate homeserver.yml

### ISSUE THREAD

**Issue by pomland-94** [element-hq/synapse#17922]
When i Install Matrix Synapse on Debian 12 Bookworm (AMD64) in a virtualenv which i create i get the following error:

```shell
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/app/homeserver.py", line 43, in <module>
from synapse.app import _base
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/app/_base.py", line 71, in <module>
from synapse.events.auto_accept_invites import InviteAutoAccepter
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/events/auto_accept_invites.py", line 28, in <module>
from synapse.module_api import EventBase, ModuleApi, run_as_background_process
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/module_api/init.py", line 58, in <module>
from synapse.handlers.account_data import ON_ACCOUNT_DATA_UPDATED_CALLBACK
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/handlers/account_data.py", line 27, in <module>
from synapse.replication.http.account_data import (
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/replication/http/init.py", line 24, in <module>
from synapse.replication.http import (
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/replication/http/account_data.py", line 28, in <module>
from synapse.replication.http._base import ReplicationEndpoint
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/replication/http/_base.py", line 38, in <module>
from synapse.http.site import SynapseRequest
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/http/site.py", line 39, in <module>
from synapse.http.proxy import ProxySite
File "/root/synapase/venv/lib/python3.11/site-packages/synapse/http/proxy.py", line 72, in <module>
_canonicalHeaderName = Headers()._encodeName
^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Headers' object has no attribute '_encodeName'
```

I create the Virtualenv as following
```shell
$mkdir synapse
$cd synapse
$python3 -m venv venv
$source venv/bin/actiavte
```

Then i upgrade some Packages and install Matrix Synapse

```shell
pip install --upgrade setuptools pip
pip install matrix-synapse
```

Then i try to generate my homeserver.yml and get the following error above:

```shell
python3 -m [synapse.app](http://synapse.app/).homeserver -c homeserver.yaml --generate-config --server-name=matrix.domain.org --report-stats=yes
```

**Comment by pomland-94** [comment]
When i manually do a 
```shell
pip install twisted==22.10.0
```
Than it work's, so i think when i do a pip install matrix-synapse the wrong version of twisted get's installed.

**Comment by erikjohnston** [comment]
Sorry about that, but the most recent version of Synapse should now support the latest Twisted.
