### ISSUE TITLE
The CI will publish artifacts on a new release, instead of using the draft one

### ISSUE THREAD

**Issue by sandhose** [element-hq/synapse#17991]
This has not been fixed by #17970

**Comment by anoadragon453** [comment]
Hopefully now fixed by https://github.com/element-hq/synapse/pull/17995. Will test during the 1.121.0rc1 release.

**Comment by anoadragon453** [comment]
![image](https://github.com/user-attachments/assets/7ef0a66a-ff15-420e-a815-8ee42e9c543c)


The CI still created a new release. Perhaps this is a change on GitHub's side? How are other projects getting around this? Are we using a different config?

**Comment by anoadragon453** [comment]
It also creates it as a published, full release, instead of a pre-release :facepalm:

**Comment by anoadragon453** [comment]
And causes the release script to break, as the release is already published. Meaning the release admin needs to resort to running the following steps manually:

<details>

<summary>Click to view release script traceback</summary>

```
*** publish ***
Publish release v1.121.0rc1 on GitHub? [Y/n]: 
Traceback (most recent call last):
  File "/home/work/code/synapse/./scripts-dev/release.py", line 974, in <module>
    cli()
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/./scripts-dev/release.py", line 756, in full
    _publish(gh_token)
  File "/home/work/code/synapse/./scripts-dev/release.py", line 452, in _publish
    release = release.update_release(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/github/GitRelease.py", line 229, in update_release
    headers, data = self._requester.requestJsonAndCheck("PATCH", self.url, input=post_parameters)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/github/Requester.py", line 586, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/work/code/synapse/.venv/lib/python3.12/site-packages/github/Requester.py", line 744, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.GithubException: 422 {"message": "Validation Failed", "errors": [{"resource": "Release", "code": "already_exists", "field": "tag_name"}], "documentation_url": "https://docs.github.com/rest/releases/releases#update-a-release", "status": "422"}
```

</details>
