### ISSUE TITLE
Synapse 1.120 ist not starting anymore after updating 

### ISSUE THREAD

**Issue by 81909ce2298f99ddafa37936ba43eaac** [element-hq/synapse#18042]
### Description

Synapse is throwing errors during startup (see Relevant log output) after the latest updates has been installed and it doesn't no start anymore. For further details about the operating system and the packages being used, please see [https://github.com/void-linux/void-packages/issues/53595](https://github.com/void-linux/void-packages/issues/53595)

### Steps to reproduce

- Synapse, python and some python libraries has been updated by using the package manager without any failure (I run "xbps-install -Su --yes" every day since many month)
- Synapse doesn't start anymore and shows the error messages shown above

### Homeserver

Own homeserver

### Synapse Version

1.120

### Installation Method

Package manager (xbps)

### Database

Postgresql 16.4, no changes between synapse was fine and it's not starting anymore

### Workers

Single process

### Platform

Linux Void (LXC container) on Alpine Linux

### Configuration

Nothing special and the whole setup worked fine before.

### Relevant log output

```shell
2024-12-20T10:38:50.05669 daemon.notice: Dec 20 11:38:50 synapse: Traceback (most recent call last):
2024-12-20T10:38:50.07886 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/bin/synapse_homeserver", line 5, in
2024-12-20T10:38:50.07924 daemon.notice: Dec 20 11:38:50 synapse: from synapse.app.homeserver import main
2024-12-20T10:38:50.07927 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/synapse/init.py", line 31, in
2024-12-20T10:38:50.07930 daemon.notice: Dec 20 11:38:50 synapse: from synapse.util.rust import check_rust_lib_up_to_date
2024-12-20T10:38:50.07950 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/synapse/util/init.py", line 32, in
2024-12-20T10:38:50.07957 daemon.notice: Dec 20 11:38:50 synapse: from twisted.internet import defer, task
2024-12-20T10:38:50.07963 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/twisted/internet/defer.py", line 48, in
2024-12-20T10:38:50.07986 daemon.notice: Dec 20 11:38:50 synapse: from twisted.internet.interfaces import IDelayedCall, IReactorTime
2024-12-20T10:38:50.07992 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/twisted/internet/interfaces.py", line 26, in
2024-12-20T10:38:50.08003 daemon.notice: Dec 20 11:38:50 synapse: from zope.interface import Attribute, Interface
2024-12-20T10:38:50.08010 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/init.py", line 57, in
2024-12-20T10:38:50.08056 daemon.notice: Dec 20 11:38:50 synapse: _wire()
2024-12-20T10:38:50.08065 daemon.notice: Dec 20 11:38:50 synapse: ~~~~~^^
2024-12-20T10:38:50.08074 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 1104, in _wire
2024-12-20T10:38:50.08080 daemon.notice: Dec 20 11:38:50 synapse: from zope.interface.interfaces import IElement
2024-12-20T10:38:50.08135 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/interfaces.py", line 54, in
2024-12-20T10:38:50.08149 daemon.notice: Dec 20 11:38:50 synapse: class IElement(Interface):
2024-12-20T10:38:50.08174 daemon.notice: Dec 20 11:38:50 synapse: ...<91 lines>...
2024-12-20T10:38:50.08183 daemon.notice: Dec 20 11:38:50 synapse: """
2024-12-20T10:38:50.08362 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 772, in init
2024-12-20T10:38:50.08372 daemon.notice: Dec 20 11:38:50 synapse: self.__attrs = self.__compute_attrs(attrs)
2024-12-20T10:38:50.08378 daemon.notice: Dec 20 11:38:50 synapse: ~~~~~~~~~~~~~~~~~~~~^^^^^^^
2024-12-20T10:38:50.08383 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 791, in __compute_attrs
2024-12-20T10:38:50.08388 daemon.notice: Dec 20 11:38:50 synapse: aname: update_value(aname, aval)
2024-12-20T10:38:50.08393 daemon.notice: Dec 20 11:38:50 synapse: ~~~~~~~~~~~~^^^^^^^^^^^^^
2024-12-20T10:38:50.08429 daemon.notice: Dec 20 11:38:50 synapse: File "/usr/lib/python3.13/site-packages/zope/interface/interface.py", line 787, in update_value
2024-12-20T10:38:50.08436 daemon.notice: Dec 20 11:38:50 synapse: raise InvalidInterface("Concrete attribute, " + aname)
```

### Anything else that would be useful to know?

Nothing

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
This issue has been fixed by the Linux Void maintainers with new versions of synapse and several python libraries (see https://github.com/void-linux/void-packages/pull/53402 for further details about the changes).

**Comment by 81909ce2298f99ddafa37936ba43eaac** [comment]
This issue has been fixed by the Linux Void maintainers with new versions of synapse and several python libraries (see https://github.com/void-linux/void-packages/pull/53402 for further details about the changes).
